site_name: ICT Chat Guide
site_url: http://insertcointheater.com
pages:
- Home: 'index.md'
- Rules: 'rules.md'
- Tokens: 'tokens.md'
- Tickets: 'tickets.md'
- Giveaways: 'giveaways.md'
- Xbox Club: 'xboxclub.md'
- Community Game Nights: 'communitygamenights.md'